services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3002:3002
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - APP_PORT=3002
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:12.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tech-challenge-product-catalog-db
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379

networks:
  default:
    name: tech-challenge-product-catalog-network
